openapi: 3.0.3
info:
  title: MechMagic AutoWorx API
  description: This API provides endpoints for managing a mechanic shop, including services, inventory, service tickets, mechanic information, and customer information.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
security:
  - CustomerToken: []
  - MechanicToken: []
tags:
  - name: CustomerAccount
    description: Operations for Account Information associated with Customers
  - name: Customer
    description: Operations for Customer Information
  - name: Inventory
    description: Operations for Inventory Information associated with ServiceItems
  - name: Invoices
    description: Operations for Invoice Information associated with ServiceTickets
  - name: MechanicAccount
    description: Operations for Account Information associated with Mechanics
  - name: Mechanic
    description: Operations for Mechanic Information
  - name: MechanicTicket
    description: Operations for Mechanic Ticket Information associated with Mechanics, Services, ServiceItems, and ServiceTickets
  - name: ServiceItem
    description: Operations for Service Item Information associated with Services and/or MechanicTickets
  - name: Service
    description: Operations for Service Information associated with ServiceItems and MechanicTickets
  - name: ServiceTicket
    description: Operations for Service Ticket Information associated with Customers, Vehicles, and Invoices
  - name: Vehicle
    description: Operations for Vehicle Information associated with Customers and ServiceTickets
paths: {}
components:
  schemas:
    Customer:
      type: object
      required:
        - name
        - email
        - phone
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
        phone:
          type: string
          minLength: 10
          maxLength: 100
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-Vehicle'
        account:
          $ref: '#/components/schemas/schemas-CustomerAccount'
        service_tickets:
          type: array
          items:
            $ref: '#/components/schemas/customers_components-schemas-ServiceTicket'
    schemas-Customer:
      allOf:
        - $ref: '#/components/schemas/Customer'
        - type: object
          properties:
            vehicles:
              not: {}
            id:
              not: {}
            account:
              not: {}
            service_tickets:
              not: {}
    Vehicle:
      type: object
      required:
        - VIN
        - year
        - make
        - model
        - mileage
        - customer_id
      properties:
        VIN:
          type: string
          minLength: 17
          maxLength: 100
        year:
          type: integer
        make:
          type: string
          minLength: 1
          maxLength: 100
        model:
          type: string
          minLength: 1
          maxLength: 100
        mileage:
          type: integer
        customer_id:
          type: integer
        customer:
          $ref: '#/components/schemas/schemas-Customer'
        service_tickets:
          type: array
          items:
            $ref: '#/components/schemas/vehicles_components-schemas-ServiceTicket'
    schemas-Vehicle:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
        - type: object
          properties:
            VIN:
              not: {}
            customer_id:
              not: {}
            customer:
              not: {}
            service_tickets:
              not: {}
    ServiceTicket:
      type: object
      required:
        - service_desc
        - VIN
      properties:
        id:
          type: integer
        service_date:
          type: string
          format: date
        service_desc:
          type: string
        VIN:
          type: string
          minLength: 17
          maxLength: 255
        customer_id:
          type: integer
        vehicle:
          $ref: '#/components/schemas/schemas-Vehicle'
        customer:
          $ref: '#/components/schemas/schemas-Customer'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-MechanicTicket'
        invoice:
          $ref: '#/components/schemas/schemas-Invoice'
    schemas-ServiceTicket:
      allOf:
        - $ref: '#/components/schemas/ServiceTicket'
        - type: object
          properties:
            id:
              not: {}
            mechanic_tickets:
              not: {}
    Mechanic:
      type: object
      properties:
        name:
          type: string
    ServiceItem:
      type: object
      required:
        - item_id
        - quantity
      properties:
        id:
          type: integer
        item_id:
          type: integer
        quantity:
          type: integer
          minimum: 1
        service_id:
          type: integer
        inventory:
          $ref: '#/components/schemas/schemas-Inventory'
        service:
          $ref: '#/components/schemas/schemas-Service'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/schemas-MechanicTicket'
    schemas-ServiceItem:
      allOf:
        - $ref: '#/components/schemas/ServiceItem'
        - type: object
          properties:
            service_id:
              not: {}
            service:
              not: {}
            mechanic_tickets:
              not: {}
    Inventory:
      type: object
      required:
        - name
        - stock
        - price
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        stock:
          type: integer
          minimum: 0
        price:
          type: number
          format: float
          minimum: 0
        service_items:
          type: array
          items:
            $ref: '#/components/schemas/schemas-ServiceItem'
    schemas-Inventory:
      allOf:
        - $ref: '#/components/schemas/Inventory'
        - type: object
          properties:
            id:
              not: {}
            service_items:
              not: {}
    Service:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        price:
          type: number
          format: float
          minimum: 0
        service_items:
          type: array
          items:
            $ref: '#/components/schemas/schemas-ServiceItem'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/schemas-MechanicTicket'
    schemas-Service:
      allOf:
        - $ref: '#/components/schemas/Service'
        - type: object
          properties:
            id:
              not: {}
            service_items:
              not: {}
            mechanic_tickets:
              not: {}
    MechanicTicket:
      type: object
      required:
        - service_ticket_id
      properties:
        id:
          type: integer
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        hours_worked:
          type: number
          format: float
        service_ticket_id:
          type: integer
        mechanic_id:
          type: integer
        service_ticket:
          $ref: '#/components/schemas/schemas-ServiceTicket'
        mechanic:
          $ref: '#/components/schemas/Mechanic'
        services:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-Service'
        additional_items:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-ServiceItem'
    schemas-MechanicTicket:
      allOf:
        - $ref: '#/components/schemas/MechanicTicket'
        - type: object
          properties:
            hours_worked:
              not: {}
            service_ticket_id:
              not: {}
            service_ticket:
              not: {}
            mechanic:
              not: {}
            services:
              not: {}
            additional_items:
              not: {}
    components-schemas-Service:
      allOf:
        - $ref: '#/components/schemas/Service'
        - type: object
          properties:
            id:
              not: {}
            mechanic_tickets:
              not: {}
    components-schemas-ServiceItem:
      allOf:
        - $ref: '#/components/schemas/ServiceItem'
        - type: object
          properties:
            mechanic_tickets:
              not: {}
    components-schemas-MechanicTicket:
      allOf:
        - $ref: '#/components/schemas/MechanicTicket'
        - type: object
          properties:
            service_ticket:
              not: {}
    components-schemas-ServiceTicket:
      allOf:
        - $ref: '#/components/schemas/ServiceTicket'
        - type: object
          properties:
            invoice:
              not: {}
            id:
              not: {}
    Invoice:
      type: object
      required:
        - paid
        - service_ticket_id
      properties:
        id:
          type: integer
        invoice_date:
          type: string
          format: date
        total:
          type: number
          format: float
        paid:
          type: boolean
        service_ticket_id:
          type: integer
        service_ticket:
          $ref: '#/components/schemas/components-schemas-ServiceTicket'
    schemas-Invoice:
      allOf:
        - $ref: '#/components/schemas/Invoice'
        - type: object
          properties:
            service_ticket:
              not: {}
            service_ticket_id:
              not: {}
    vehicles_components-schemas-ServiceTicket:
      allOf:
        - $ref: '#/components/schemas/ServiceTicket'
        - type: object
          properties:
            VIN:
              not: {}
            customer_id:
              not: {}
            customer:
              not: {}
            vehicle:
              not: {}
    components-schemas-Vehicle:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
        - type: object
          properties:
            customer_id:
              not: {}
            customer:
              not: {}
            service_tickets:
              not: {}
    components-schemas-Customer:
      allOf:
        - $ref: '#/components/schemas/Customer'
        - type: object
          properties:
            id:
              not: {}
            email:
              not: {}
            account:
              not: {}
    CustomerAccount:
      type: object
      required:
        - customer_id
        - email
        - password
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
        customer:
          $ref: '#/components/schemas/components-schemas-Customer'
    schemas-CustomerAccount:
      allOf:
        - $ref: '#/components/schemas/CustomerAccount'
        - type: object
          properties:
            customer_id:
              not: {}
            customer:
              not: {}
    customers_components-schemas-ServiceTicket:
      allOf:
        - $ref: '#/components/schemas/ServiceTicket'
        - type: object
          properties:
            customer_id:
              not: {}
            customer:
              not: {}
    MechanicAccount:
      type: object
      required:
        - mechanic_id
        - email
        - password
      properties:
        - id: null
          type: integer
        - role: null
          type: string
          default: Mechanic
        - mechanic_id: null
          type: integer
        - email: null
          type: string
          format: email
        - password: null
          type: string
          minLength: 8
          maxLength: 100
        - mechanic: null
          $ref: '#/components/schemas/Mechanic'
    schemas-MechanicAccount:
      allOf:
        - $ref: '#/components/schemas/MechanicAccount'
        - type: object
          properties:
            mechanic_id:
              not: {}
            mechanic:
              not: {}
    mechanics_components-schemas-MechanicTicket:
      allOf:
        - $ref: '#/components/schemas/MechanicTicket'
        - type: object
          properties:
            mechanic_id:
              not: {}
            mechanic:
              not: {}
    schemas-Mechanic:
      type: object
      required:
        - name
        - email
        - phone
        - salary
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
        phone:
          type: string
          minLength: 10
          maxLength: 100
        salary:
          type: number
          format: float
        account:
          $ref: '#/components/schemas/schemas-MechanicAccount'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/mechanics_components-schemas-MechanicTicket'
    customerUpdate_components-schemas-ServiceTicket:
      allOf:
        - $ref: '#/components/schemas/ServiceTicket'
        - type: object
          properties:
            customer_id:
              not: {}
            customer:
              not: {}
    CustomerUpdate:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
        phone:
          type: string
          minLength: 10
          maxLength: 100
        vehicles:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-Vehicle'
        account:
          $ref: '#/components/schemas/schemas-CustomerAccount'
        service_tickets:
          type: array
          items:
            $ref: '#/components/schemas/customerUpdate_components-schemas-ServiceTicket'
    CustomerAccountUpdate:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
        customer:
          $ref: '#/components/schemas/components-schemas-Customer'
    InventoryUpdate:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        stock:
          type: integer
          minimum: 0
        price:
          type: number
          format: float
          minimum: 0
        service_items:
          type: array
          items:
            $ref: '#/components/schemas/schemas-ServiceItem'
    InvoiceUpdate:
      type: object
      properties:
        id:
          type: integer
        invoice_date:
          type: string
          format: date
        total:
          type: number
          format: float
        paid:
          type: boolean
        service_ticket_id:
          type: integer
        service_ticket:
          $ref: '#/components/schemas/components-schemas-ServiceTicket'
    MechanicAccountUpdate:
      type: object
      properties:
        - id: null
          type: integer
        - role: null
          type: string
          default: Mechanic
        - mechanic_id: null
          type: integer
        - email: null
          type: string
          format: email
        - password: null
          type: string
          minLength: 8
          maxLength: 100
        - mechanic: null
          $ref: '#/components/schemas/Mechanic'
    mechanicUpdate_components-schemas-MechanicTicket:
      allOf:
        - $ref: '#/components/schemas/MechanicTicket'
        - type: object
          properties:
            mechanic_id:
              not: {}
            mechanic:
              not: {}
    MechanicUpdate:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
        phone:
          type: string
          minLength: 10
          maxLength: 100
        salary:
          type: number
          format: float
        account:
          $ref: '#/components/schemas/schemas-MechanicAccount'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/mechanicUpdate_components-schemas-MechanicTicket'
    MechanicTicketUpdate:
      type: object
      properties:
        id:
          type: integer
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        hours_worked:
          type: number
          format: float
        service_ticket_id:
          type: integer
        mechanic_id:
          type: integer
        service_ticket:
          $ref: '#/components/schemas/schemas-ServiceTicket'
        mechanic:
          $ref: '#/components/schemas/Mechanic'
        services:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-Service'
        additional_items:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-ServiceItem'
    ServiceItemUpdate:
      type: object
      properties:
        id:
          type: integer
        item_id:
          type: integer
        quantity:
          type: integer
          minimum: 1
        service_id:
          type: integer
        inventory:
          $ref: '#/components/schemas/schemas-Inventory'
        service:
          $ref: '#/components/schemas/schemas-Service'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/schemas-MechanicTicket'
    ServiceUpdate:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        price:
          type: number
          format: float
          minimum: 0
        service_items:
          type: array
          items:
            $ref: '#/components/schemas/schemas-ServiceItem'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/schemas-MechanicTicket'
    ServiceTicketUpdate:
      type: object
      properties:
        id:
          type: integer
        service_date:
          type: string
          format: date
        service_desc:
          type: string
        VIN:
          type: string
          minLength: 17
          maxLength: 255
        customer_id:
          type: integer
        vehicle:
          $ref: '#/components/schemas/schemas-Vehicle'
        customer:
          $ref: '#/components/schemas/schemas-Customer'
        mechanic_tickets:
          type: array
          items:
            $ref: '#/components/schemas/components-schemas-MechanicTicket'
        invoice:
          $ref: '#/components/schemas/schemas-Invoice'
    vehicleUpdate_components-schemas-ServiceTicket:
      allOf:
        - $ref: '#/components/schemas/ServiceTicket'
        - type: object
          properties:
            VIN:
              not: {}
            customer_id:
              not: {}
            customer:
              not: {}
            vehicle:
              not: {}
    VehicleUpdate:
      type: object
      properties:
        VIN:
          type: string
          minLength: 17
          maxLength: 100
        year:
          type: integer
        make:
          type: string
          minLength: 1
          maxLength: 100
        model:
          type: string
          minLength: 1
          maxLength: 100
        mileage:
          type: integer
        customer_id:
          type: integer
        customer:
          $ref: '#/components/schemas/schemas-Customer'
        service_tickets:
          type: array
          items:
            $ref: '#/components/schemas/vehicleUpdate_components-schemas-ServiceTicket'
    CustomerLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
    MechanicLogin:
      type: object
      required:
        - email
        - password
      properties:
        id:
          type: integer
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
  securitySchemes:
    CustomerToken:
      type: apiKey
      in: header
      name: Authorization
      description: |
        Use the customer Bearer token provided after login. Format: `Bearer {token}`. Token is generated via: - Algorithm: HS256 - Payload: 
          - `sub`: User ID
          - `exp`: 24 hours from issue
          - `iat`: Issued at timestamp
    MechanicToken:
      type: apiKey
      in: header
      name: Authorization
      description: |
        Use the mechanic Bearer token provided after login. Format: `Bearer {token}`. Token is generated via: - Algorithm: HS256 - Payload: 
          - `sub`: User ID
          - `role`: Always "Mechanic"
          - `exp`: 24 hours from issue
          - `iat`: Issued at timestamp
  examples:
    LoginSuccess:
      summary: Successful login, returns auth token
      value:
        status: success
        message: Successfully Logged In
        auth_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    Customer1:
      value:
        id: 1
        name: Selina Kyle
        email: kittySoftPaws@example.com
        phone: 777-777-1313
        vehicles:
          - VIN: 1FA6P8TH4L5500001
            year: 2020
            make: Ford
            model: Mustang
            mileage: 15000
        account:
          - id: 1
            password: $2a$12$VdjVpUg7VPVy8pYG3QzP0e9dUT9yFlUIAxViRD16uLCfMaInP9GP6
        service_tickets:
          - id: 1
            service_date: '2023-10-01'
            service_desc: Oil change
            VIN: 1FA6P8TH4L5500001
            vehicle:
              - year: 2020
                make: Ford
                model: Mustang
                mileage: 15000
    Customer2:
      value:
        id: 2
        name: Bruce Wayne
        email: darkKnightRides@example.com
        phone: 212-000-1940
        vehicles:
          - VIN: WAUZZZF49JA000002
            year: 2022
            make: Lamborghini
            model: Aventador
            mileage: 3800
        account:
          - id: 2
            password: $2a$12$z3uAKlX8HoTbJmlM3pD.pOxe.ub3NQTfGTb1Jb6fOo9/ld/uxkIgC
        service_tickets:
          - id: 2
            service_date: '2024-01-15'
            service_desc: Armor plating upgrade
            VIN: WAUZZZF49JA000002
            vehicle:
              - year: 2022
                make: Lamborghini
                model: Aventador
                mileage: 3800
    Customer3:
      value:
        id: 3
        name: Jack Napier
        email: laughsRfree@example.com
        phone: 666-123-0000
        vehicles:
          - VIN: JHMFA16586S000003
            year: 2012
            make: Dodge
            model: Charger
            mileage: 98765
        account:
          - id: 3
            password: $2a$12$m.ES8I4rE6pBJ0h8od1c/.amgCyT31hF/NhSHgQCrIwovMcAIGOwa
        service_tickets:
          - id: 3
            service_date: '2024-03-31'
            service_desc: Custom horn install (laugh track)
            VIN: JHMFA16586S000003
            vehicle:
              - year: 2012
                make: Dodge
                model: Charger
                mileage: 98765
    Customer4:
      value:
        id: 4
        name: Harleen Quinzel
        email: puddin4life@example.com
        phone: 555-666-9901
        vehicles:
          - VIN: KM8JU3AG6BU000004
            year: 2018
            make: Mini
            model: Cooper
            mileage: 22300
        account:
          - id: 4
            password: $2a$12$01T6r3QDdNLqlkFp4F3EAe02hQmu9ciZWheutqlSLDUxUuQBj8HWK
        service_tickets:
          - id: 4
            service_date: '2024-02-14'
            service_desc: Tire rotation and bubblegum scent refresh
            VIN: KM8JU3AG6BU000004
            vehicle:
              - year: 2018
                make: Mini
                model: Cooper
                mileage: 22300
    Customer5:
      value:
        id: 5
        name: Pamela Isley
        email: rootedQueen@example.com
        phone: 444-888-3737
        vehicles:
          - VIN: YV4952DL3F2000005
            year: 2019
            make: Tesla
            model: Model S
            mileage: 12345
        account:
          - id: 5
            password: $2a$12$5v4cnQ7wWRbulkHnxZyghuMpPH5Zeka5YzxYQWGG9VcyqV7LGJWVK
        service_tickets:
          - id: 5
            service_date: '2023-11-20'
            service_desc: Biofuel filter replacement
            VIN: YV4952DL3F2000005
            vehicle:
              - year: 2019
                make: Tesla
                model: Model S
                mileage: 12345
    Customer6:
      value:
        id: 6
        name: Edward Nigma
        email: r1ddleM3Th1s@example.com
        phone: 313-313-3133
        vehicles:
          - VIN: 1C4RJFBG0JC000006
            year: 2021
            make: Jaguar
            model: XF
            mileage: 28900
        account:
          - id: 6
            password: $2a$12$czcd.25AqAJUNmhJ0EAc7u5UUjkkmAB5y09wWcSEK2YH7vAb/taYe
        service_tickets:
          - id: 6
            service_date: '2024-04-01'
            service_desc: ECU reprogrammed for puzzle mode
            VIN: 1C4RJFBG0JC000006
            vehicle:
              - year: 2021
                make: Jaguar
                model: XF
                mileage: 28900
    AllCustomers:
      summary: A list of All Customers
      value:
        - id: 1
          name: Selina Kyle
          email: kittySoftPaws@example.com
          phone: 777-777-1313
          vehicles:
            - VIN: 1FA6P8TH4L5500001
              year: 2020
              make: Ford
              model: Mustang
              mileage: 15000
          account:
            - id: 1
              password: $2a$12$VdjVpUg7VPVy8pYG3QzP0e9dUT9yFlUIAxViRD16uLCfMaInP9GP6
          service_tickets:
            - id: 1
              service_date: '2023-10-01'
              service_desc: Oil change
              VIN: 1FA6P8TH4L5500001
              vehicle:
                - year: 2020
                  make: Ford
                  model: Mustang
                  mileage: 15000
        - id: 2
          name: Bruce Wayne
          email: darkKnightRides@example.com
          phone: 212-000-1940
          vehicles:
            - VIN: WAUZZZF49JA000002
              year: 2022
              make: Lamborghini
              model: Aventador
              mileage: 3800
          account:
            - id: 2
              password: $2a$12$z3uAKlX8HoTbJmlM3pD.pOxe.ub3NQTfGTb1Jb6fOo9/ld/uxkIgC
          service_tickets:
            - id: 2
              service_date: '2024-01-15'
              service_desc: Armor plating upgrade
              VIN: WAUZZZF49JA000002
              vehicle:
                - year: 2022
                  make: Lamborghini
                  model: Aventador
                  mileage: 3800
        - id: 3
          name: Jack Napier
          email: laughsRfree@example.com
          phone: 666-123-0000
          vehicles:
            - VIN: JHMFA16586S000003
              year: 2012
              make: Dodge
              model: Charger
              mileage: 98765
          account:
            - id: 3
              password: $2a$12$m.ES8I4rE6pBJ0h8od1c/.amgCyT31hF/NhSHgQCrIwovMcAIGOwa
          service_tickets:
            - id: 3
              service_date: '2024-03-31'
              service_desc: Custom horn install (laugh track)
              VIN: JHMFA16586S000003
              vehicle:
                - year: 2012
                  make: Dodge
                  model: Charger
                  mileage: 98765
        - id: 4
          name: Harleen Quinzel
          email: puddin4life@example.com
          phone: 555-666-9901
          vehicles:
            - VIN: KM8JU3AG6BU000004
              year: 2018
              make: Mini
              model: Cooper
              mileage: 22300
          account:
            - id: 4
              password: $2a$12$01T6r3QDdNLqlkFp4F3EAe02hQmu9ciZWheutqlSLDUxUuQBj8HWK
          service_tickets:
            - id: 4
              service_date: '2024-02-14'
              service_desc: Tire rotation and bubblegum scent refresh
              VIN: KM8JU3AG6BU000004
              vehicle:
                - year: 2018
                  make: Mini
                  model: Cooper
                  mileage: 22300
        - id: 5
          name: Pamela Isley
          email: rootedQueen@example.com
          phone: 444-888-3737
          vehicles:
            - VIN: YV4952DL3F2000005
              year: 2019
              make: Tesla
              model: Model S
              mileage: 12345
          account:
            - id: 5
              password: $2a$12$5v4cnQ7wWRbulkHnxZyghuMpPH5Zeka5YzxYQWGG9VcyqV7LGJWVK
          service_tickets:
            - id: 5
              service_date: '2023-11-20'
              service_desc: Biofuel filter replacement
              VIN: YV4952DL3F2000005
              vehicle:
                - year: 2019
                  make: Tesla
                  model: Model S
                  mileage: 12345
        - id: 6
          name: Edward Nigma
          email: r1ddleM3Th1s@example.com
          phone: 313-313-3133
          vehicles:
            - VIN: 1C4RJFBG0JC000006
              year: 2021
              make: Jaguar
              model: XF
              mileage: 28900
          account:
            - id: 6
              password: $2a$12$czcd.25AqAJUNmhJ0EAc7u5UUjkkmAB5y09wWcSEK2YH7vAb/taYe
          service_tickets:
            - id: 6
              service_date: '2024-04-01'
              service_desc: ECU reprogrammed for puzzle mode
              VIN: 1C4RJFBG0JC000006
              vehicle:
                - year: 2021
                  make: Jaguar
                  model: XF
                  mileage: 28900
    Mechanic1:
      value:
        id: 1
        name: Johnny Blaze
        email: hellcycle.tuneup@example.com
        phone: 999-666-0001
        salary: 51
        account:
          - id: 1
            email: hellcycle.tuneup@example.com
            password: $2a$12$oHHaiIdYdPZiRMdC7uZyj.o80Rso.15iiEZrz5IkRnJD.P9thHFAu
        mechanic_tickets:
          - id: 1
            start_date: '2024-03-01'
            end_date: '2024-03-02'
            hours_worked: 8.5
            service_ticket:
              - id: 1
                service_date: '2023-10-01'
                service_desc: Oil change
                VIN: 1FA6P8TH4L5500001
            services:
              - id: 1
                name: Flameproof Exhaust Mod
                price: 299.99
            additional_items:
              - id: 1
                item_id: 101
                quantity: 2
                inventory:
                  id: 101
                  name: Fireproof Exhaust Wrap
                  stock: 50
                  price: 25
          - id: 2
            start_date: '2024-03-03'
            end_date: '2024-03-03'
            hours_worked: 6
            service_ticket:
              - id: 2
                service_date: '2024-01-15'
                service_desc: Armor plating upgrade
                VIN: WAUZZZF49JA000002
            services:
              - id: 2
                name: Chassis Armor Buff
                price: 449.99
            additional_items:
              - id: 2
                item_id: 102
                quantity: 1
                inventory:
                  id: 102
                  name: Titanium Reinforcement Kit
                  stock: 5
                  price: 399.99
    Mechanic2:
      value:
        id: 2
        name: Anthony Stark
        email: ironman.tech@example.com
        phone: 212-777-IRON
        salary: 88
        account:
          - id: 2
            email: ironman.tech@example.com
            password: $2a$12$KsLo/6I6/D7MRj6.j9s9YeRDB/x/y.B2bu/wbKmKRweFalbnz3QN2
        mechanic_tickets:
          - id: 3
            start_date: '2024-04-01'
            end_date: '2024-04-03'
            hours_worked: 16
            service_ticket:
              - id: 3
                service_date: '2024-03-31'
                service_desc: Custom horn install (laugh track)
                VIN: JHMFA16586S000003
            services:
              - id: 3
                name: AI Diagnostic
                price: 149
            additional_items:
              - id: 3
                item_id: 103
                quantity: 1
                inventory:
                  id: 103
                  name: Nano-calibrated Sensors
                  stock: 7
                  price: 599.99
          - id: 5
            start_date: '2024-04-10'
            end_date: '2024-04-11'
            hours_worked: 9
            service_ticket:
              - id: 5
                service_date: '2023-11-20'
                service_desc: Biofuel filter replacement
                VIN: YV4952DL3F2000005
            services:
              - id: 5
                name: Environmental System Tuning
                price: 299
            additional_items:
              - id: 5
                item_id: 105
                quantity: 2
                inventory:
                  id: 105
                  name: Organic Fuel Cell
                  stock: 12
                  price: 199.99
    Mechanic3:
      value:
        id: 3
        name: James Howlett
        email: adamantiumGarage@example.com
        phone: 867-530-XMEN
        salary: 43
        account:
          - id: 3
            email: adamantiumGarage@example.com
            password: $2a$12$189HX7GNr9mM/RC2gvlb5ufmKL5w6EcgpHx4uTwIxlbhcWCnYK69a
        mechanic_tickets:
          - id: 4
            start_date: '2024-01-12'
            end_date: '2024-01-12'
            hours_worked: 5
            service_ticket:
              - id: 4
                service_date: '2024-02-14'
                service_desc: Tire rotation and bubblegum scent refresh
                VIN: KM8JU3AG6BU000004
            services:
              - id: 4
                name: Claw Guard Installation
                price: 189.99
            additional_items:
              - id: 4
                item_id: 104
                quantity: 4
                inventory:
                  id: 104
                  name: Reinforced Seat Covers
                  stock: 20
                  price: 45
          - id: 6
            start_date: '2024-04-14'
            end_date: '2024-04-14'
            hours_worked: 6
            service_ticket:
              - id: 6
                service_date: '2024-04-01'
                service_desc: ECU reprogrammed for puzzle mode
                VIN: 1C4RJFBG0JC000006
            services:
              - id: 6
                name: System Decryption
                price: 399.99
            additional_items:
              - id: 6
                item_id: 106
                quantity: 3
                inventory:
                  id: 106
                  name: Neural Unlock Chip
                  stock: 10
                  price: 349
    AllMechanics:
      summary: List of All Mechanics
      value:
        - id: 1
          name: Johnny Blaze
          email: hellcycle.tuneup@example.com
          phone: 999-666-0001
          salary: 51
          account:
            - id: 1
              email: hellcycle.tuneup@example.com
              password: $2a$12$oHHaiIdYdPZiRMdC7uZyj.o80Rso.15iiEZrz5IkRnJD.P9thHFAu
          mechanic_tickets:
            - id: 1
              start_date: '2024-03-01'
              end_date: '2024-03-02'
              hours_worked: 8.5
              service_ticket:
                - id: 1
                  service_date: '2023-10-01'
                  service_desc: Oil change
                  VIN: 1FA6P8TH4L5500001
              services:
                - id: 1
                  name: Flameproof Exhaust Mod
                  price: 299.99
              additional_items:
                - id: 1
                  item_id: 101
                  quantity: 2
                  inventory:
                    id: 101
                    name: Fireproof Exhaust Wrap
                    stock: 50
                    price: 25
            - id: 2
              start_date: '2024-03-03'
              end_date: '2024-03-03'
              hours_worked: 6
              service_ticket:
                - id: 2
                  service_date: '2024-01-15'
                  service_desc: Armor plating upgrade
                  VIN: WAUZZZF49JA000002
              services:
                - id: 2
                  name: Chassis Armor Buff
                  price: 449.99
              additional_items:
                - id: 2
                  item_id: 102
                  quantity: 1
                  inventory:
                    id: 102
                    name: Titanium Reinforcement Kit
                    stock: 5
                    price: 399.99
        - id: 2
          name: Anthony Stark
          email: ironman.tech@example.com
          phone: 212-777-IRON
          salary: 88
          account:
            - id: 2
              email: ironman.tech@example.com
              password: $2a$12$KsLo/6I6/D7MRj6.j9s9YeRDB/x/y.B2bu/wbKmKRweFalbnz3QN2
          mechanic_tickets:
            - id: 3
              start_date: '2024-04-01'
              end_date: '2024-04-03'
              hours_worked: 16
              service_ticket:
                - id: 3
                  service_date: '2024-03-31'
                  service_desc: Custom horn install (laugh track)
                  VIN: JHMFA16586S000003
              services:
                - id: 3
                  name: AI Diagnostic
                  price: 149
              additional_items:
                - id: 3
                  item_id: 103
                  quantity: 1
                  inventory:
                    id: 103
                    name: Nano-calibrated Sensors
                    stock: 7
                    price: 599.99
            - id: 5
              start_date: '2024-04-10'
              end_date: '2024-04-11'
              hours_worked: 9
              service_ticket:
                - id: 5
                  service_date: '2023-11-20'
                  service_desc: Biofuel filter replacement
                  VIN: YV4952DL3F2000005
              services:
                - id: 5
                  name: Environmental System Tuning
                  price: 299
              additional_items:
                - id: 5
                  item_id: 105
                  quantity: 2
                  inventory:
                    id: 105
                    name: Organic Fuel Cell
                    stock: 12
                    price: 199.99
        - id: 3
          name: James Howlett
          email: adamantiumGarage@example.com
          phone: 867-530-XMEN
          salary: 43
          account:
            - id: 3
              email: adamantiumGarage@example.com
              password: $2a$12$189HX7GNr9mM/RC2gvlb5ufmKL5w6EcgpHx4uTwIxlbhcWCnYK69a
          mechanic_tickets:
            - id: 4
              start_date: '2024-01-12'
              end_date: '2024-01-12'
              hours_worked: 5
              service_ticket:
                - id: 4
                  service_date: '2024-02-14'
                  service_desc: Tire rotation and bubblegum scent refresh
                  VIN: KM8JU3AG6BU000004
              services:
                - id: 4
                  name: Claw Guard Installation
                  price: 189.99
              additional_items:
                - id: 4
                  item_id: 104
                  quantity: 4
                  inventory:
                    id: 104
                    name: Reinforced Seat Covers
                    stock: 20
                    price: 45
            - id: 6
              start_date: '2024-04-14'
              end_date: '2024-04-14'
              hours_worked: 6
              service_ticket:
                - id: 6
                  service_date: '2024-04-01'
                  service_desc: ECU reprogrammed for puzzle mode
                  VIN: 1C4RJFBG0JC000006
              services:
                - id: 6
                  name: System Decryption
                  price: 399.99
              additional_items:
                - id: 6
                  item_id: 106
                  quantity: 3
                  inventory:
                    id: 106
                    name: Neural Unlock Chip
                    stock: 10
                    price: 349
  requestBodies:
    CustomerCreate:
      description: Customer Information Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Customer'
    CustomerUpdate:
      description: Customer Information Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomerUpdate'
    CustomerAccountCreate:
      description: Customer Account Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomerAccount'
    CustomerAccountUpdate:
      description: Customer Account Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomerAccountUpdate'
    CustomerLogin:
      description: Customer Account Login Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomerLogin'
    InventoryCreate:
      description: Inventory Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'
    InventoryUpdate:
      description: Inventory Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InventoryUpdate'
    InvoiceCreate:
      description: Invoice Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Invoice'
    InvoiceUpdate:
      description: Invoice Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvoiceUpdate'
    MechanicAccountCreate:
      description: Mechanic Account Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MechanicAccount'
    MechanicAccountUpdate:
      description: Mechanic Account Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MechanicAccountUpdate'
    MechanicLogin:
      description: Mechanic Account Login Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MechanicLogin'
    MechanicCreate:
      description: Mechanic Information Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/schemas-Mechanic'
    MechanicUpdate:
      description: Mechanic Information Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MechanicUpdate'
    MechanicTicketCreate:
      description: Mechanic Ticket Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MechanicTicket'
    MechanicTicketUpdate:
      description: Mechanic Ticket Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MechanicTicketUpdate'
    ServiceItemCreate:
      description: Service Item Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceItem'
    ServiceItemUpdate:
      description: Service Item Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceItemUpdate'
    ServiceCreate:
      description: Service Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Service'
    ServiceUpdate:
      description: Service Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceUpdate'
    ServiceTicketCreate:
      description: Service Ticket Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceTicket'
    ServiceTicketUpdate:
      description: Service Ticket Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceTicketUpdate'
    VehicleCreate:
      description: Vehicle Creation Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Vehicle'
    VehicleUpdate:
      description: Vehicle Update Request Body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VehicleUpdate'
  responses:
    200Login:
      description: Successful login, returns auth token
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string
              auth_token:
                type: string
          examples:
            LoginSuccess:
              $ref: '#/components/examples/LoginSuccess'
    200AccountDelete:
      description: Successful Account Deletion
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Account Successfully Deleted
    200CustomerDelete:
      description: Successful Customer Deletion
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Customer Successfully Deleted
    200MechanicDelete:
      description: Successful Mechanic Deletion
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Mechanic Successfully Deleted
    400Login:
      description: Bad Request, Missing Credentials
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Expecting Email and Password
    401Login:
      description: Unauthorized, Invalid Credentials
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Credentials
    404CustomerAccount:
      description: Not Found, Customer or Account Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Customer or Account not found
    404Customer:
      description: Not Found, Customer Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Customer ID or Customer Not in Database
    404Inventory:
      description: Not Found, Inventory Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Inventory ID or Inventory Not in Database
    404Invoice:
      description: Not Found, Invoice Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Invoice ID or Invoice Not in Database
    404MechanicAccount:
      description: Not Found, Mechanic or Account Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Mechanic or Account not found
    404Mechanic:
      description: Not Found, Mechanic Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Mechanic ID or Mechanic Not in Database
    404MechanicTicket:
      description: Not Found, Mechanic Ticket Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Mechanic Ticket ID or Mechanic Ticket Not in Database
    404MechanicTicketServices:
      description: Not Found, Mechanic Ticket Service Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: One or More Service IDs are Invalid
    400Items:
      description: Bad Request, Missing Items Data
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Each Additional Item Must Include 'item_id' and 'quantity'
    404ServiceItem:
      description: Not Found, Service Item Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Service Item ID or Service Item Not in Database
    404ServiceTicket:
      description: Not Found, Service Ticket Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Service Ticket ID or Service Ticket Not in Database
    404Vehicle:
      description: Not Found, Vehicle Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid VIN or Vehicle Not in Database
